import type { Metadata } from "next";
import { Check, Compass, Globe2, Handshake, Layers3, MapPinned, ShieldCheck } from "lucide-react";
import { FinalCta } from "@/components/final-cta";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title:"About Agrogo", description:"Agrogo is a Morocco-based IT and digital transformation company combining consulting, project management and software delivery." };
const capabilities=["Business and process diagnosis","Requirements and solution definition","IT project management and PMO","Web and mobile software delivery","ERP/CRM implementation and integration","Deployment, training and support"];
const principles=[{icon:Compass,title:"Operational clarity",text:"We define the problem, users and workflow before choosing technology."},{icon:ShieldCheck,title:"Controlled delivery",text:"Phases, reporting, QA and acceptance keep responsibility visible."},{icon:Handshake,title:"Accountability",text:"One team connects decisions, delivery, training and continuity."},{icon:Layers3,title:"Practical architecture",text:"We select the simplest useful system that can support the real operation."}];
export default function AboutPage(){return <main id="main-content"><PageHero eyebrow="About Agrogo" title={<>Digital transformation with <em>operational discipline.</em></>} intro="Agrogo is a Morocco-based IT and digital transformation company helping organizations replace manual and fragmented work with useful digital systems." aside={<><span className="aside-label">Our mission</span><strong>To make digital transformation practical, controlled and measurable for organizations.</strong></>}/><section className="section-shell section-pad about-intro"><div><div className="eyebrow"><span/>Who we are</div><h2>Consulting, project management and software delivery in one operating model.</h2></div><div><p>We combine business understanding with technical delivery to make web, mobile and management systems succeed in real operations.</p><p>Our role covers the complete lifecycle: diagnosis, requirements, governance, development, deployment, user training, maintenance and continuous improvement.</p></div></section><section className="about-principles section-pad"><div className="section-shell"><div className="section-heading centered"><div className="eyebrow"><span/>Working principles</div><h2>How we make the work dependable</h2></div><div className="about-card-grid">{principles.map(({icon:Icon,title,text})=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section-shell section-pad capability-block"><div><div className="eyebrow"><span/>Delivery capabilities</div><h2>One team across the project lifecycle</h2><div className="capability-checks">{capabilities.map(x=><div key={x}><Check/>{x}</div>)}</div></div><div className="readiness-cards"><article><MapPinned/><h3>Local understanding</h3><p>Morocco-based delivery informed by Arabic and French workflows and local organizational constraints.</p></article><article><Globe2/><h3>International delivery readiness</h3><p>Structured reporting, acceptance, support and delivery practices suitable for Moroccan, African and European projects.</p></article></div></section><section className="about-location-section"><div className="section-shell about-location-grid"><div className="about-location-copy"><div className="eyebrow light"><span/>Where we operate</div><h2>Casablanca roots. UK presence. European delivery.</h2><p>Our Morocco office is located at 101 Najma, Casablanca. We also maintain a UK branch in London for closer communication with UK and European clients.</p><div className="about-location-lines"><span>🇲🇦 101 Najma, Casablanca, Morocco</span><span>🇬🇧 London, United Kingdom</span></div></div><div className="about-map-frame"><iframe title="Approximate Casablanca office area" src="https://www.google.com/maps?q=Casablanca%2C%20Morocco&z=12&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section><FinalCta/></main>}
