import { Bell, Check, ChevronRight, FileText, MapPin, Search } from "lucide-react";

export function DemoScreen({ type }: { type: "workflow" | "portal" | "erp" | "mobile" | "dashboard" }) {
  if (type === "mobile") return <div className="demo-device"><div className="device-notch"/><div className="device-bar"><strong>Field tasks</strong><Bell/></div><div className="device-card"><span>08:30</span><strong>Equipment inspection</strong><p><MapPin/> Assigned location</p></div><div className="device-card"><span>11:00</span><strong>Service report</strong><p><FileText/> Form and photos</p></div><button type="button">Complete task <ChevronRight/></button></div>;
  if (type === "dashboard") return <div className="demo-ui"><div className="demo-ui-top"><strong>Operations overview</strong><span>This month</span></div><div className="demo-kpis"><div><span>Requests</span><b>148</b></div><div><span>On time</span><b>92%</b></div><div><span>Open</span><b>17</b></div></div><div className="demo-chart"><i/><i/><i/><i/><i/><i/><i/><i/></div></div>;
  if (type === "erp") return <div className="demo-ui"><div className="demo-ui-top"><strong>ERP / CRM</strong><span><Search/> Search</span></div><div className="demo-table"><b>Document</b><b>Customer</b><b>Status</b><span>Q-024</span><span>Business account</span><em>Validated</em><span>INV-088</span><span>Service account</span><em>Ready</em><span>PRJ-012</span><span>Institution</span><em>Active</em></div></div>;
  if (type === "portal") return <div className="demo-ui"><div className="portal-head"><span className="portal-avatar">AB</span><div><small>Welcome back</small><strong>Account portal</strong></div><Bell/></div><div className="portal-request"><span>Latest request</span><strong>Service request #1048</strong><div><i/><i/><i/></div><small>Under review</small></div><div className="portal-actions"><span>New request</span><span>Documents</span><span>Notifications</span></div></div>;
  return <div className="demo-ui"><div className="demo-ui-top"><strong>Approval request</strong><span>REF-1052</span></div><div className="approval-flow"><div className="done"><Check/></div><i/><div className="active">2</div><i/><div>3</div></div><div className="approval-labels"><span>Submitted</span><span>Operations</span><span>Director</span></div><div className="approval-row"><span>Supporting document</span><strong><FileText/> request.pdf</strong></div><div className="approval-row"><span>Current status</span><em>Operations review</em></div></div>;
}
