export const siteConfig = {
  name: "Agrogo IT Services",
  descriptor: "Digital Transformation & Software Solutions",
  location: "Casablanca, Morocco",
  email: "contact@agrogoit.com",
  whatsapp: "+212633414884",
  mapUrl: "https://maps.app.goo.gl/XzSY8bhg2Ejn1JGq7",
  offices: [
    {
      flag: "🇲🇦",
      label: "Morocco office",
      city: "Casablanca, Morocco",
      address: "101 Najma, Casablanca, Morocco",
      phone: "+212 633 414 884",
      phoneHref: "tel:+212633414884",
      primary: true,
    },
    {
      flag: "🇬🇧",
      label: "UK branch",
      city: "London, United Kingdom",
      address: "London, UK",
      phone: "+44 7782 225704",
      phoneHref: "tel:+447782225704",
      primary: false,
    },
  ],
  linkedIn: null as string | null,
  businessHours: null as string | null,
  formEndpoint: "https://formspree.io/f/xyegrvdq",
};
