import type { Metadata } from "next";
import { Check, Flag, Gauge, GraduationCap, Search, Settings2 } from "lucide-react";
import { FinalCta } from "@/components/final-cta";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title:"Delivery Methodology", description:"Agrogo's controlled delivery approach: discovery, definition, phased delivery, QA, deployment, training, support and impact measurement." };

const phases=[
  {icon:Search,phase:"01",title:"Discover the operation",text:"Understand the real problem, users, tools, constraints and current process before proposing technology.",outputs:["Stakeholder input","Current-state process","Problem definition"]},
  {icon:Settings2,phase:"02",title:"Define the right system",text:"Prioritize the highest-value workflow and establish measurable acceptance criteria before development.",outputs:["Requirements","Priorities","Acceptance criteria"]},
  {icon:Gauge,phase:"03",title:"Deliver in controlled phases",text:"Divide large work into reviewable phases with weekly reporting, active risk management and visible ownership.",outputs:["Phased releases","Weekly reports","Decision log"]},
  {icon:Check,phase:"04",title:"Assure quality and accept",text:"Test functionality and workflows, resolve defects and obtain formal client validation before handover.",outputs:["Structured QA","Validation record","Formal acceptance"]},
  {icon:GraduationCap,phase:"05",title:"Deploy and enable users",text:"Prepare production, migrate data, train users and document the operating process before responsibility shifts.",outputs:["Production deployment","User training","Handover package"]},
  {icon:Flag,phase:"06",title:"Support and measure impact",text:"Monitor adoption, operational performance and support needs, then improve the system with evidence.",outputs:["Support plan","Adoption review","Improvement roadmap"]},
];
const principles=["Understand the operational problem before proposing technology","Begin with one high-value workflow when appropriate","Set measurable acceptance criteria before development","Divide large projects into controlled phases","Provide weekly progress reporting","Perform structured quality assurance","Obtain formal validation and acceptance","Train users before handover","Plan maintenance and support from the beginning","Measure adoption and operational impact after launch"];
export default function MethodologyPage(){return <main id="main-content"><PageHero eyebrow="How we deliver" title={<>Control the project from <em>problem to adoption.</em></>} intro="Digital transformation succeeds when responsibilities, acceptance and operational use are managed as carefully as the software." aside={<><span className="aside-label">Delivery standard</span><strong>Visible progress. Clear acceptance.</strong><p>Every phase ends with concrete outputs and a controlled decision about what happens next.</p></>}/><section className="section-shell section-pad"><div className="method-timeline">{phases.map(({icon:Icon,phase,title,text,outputs})=><article key={phase}><div className="method-marker"><Icon/></div><div className="method-phase">PHASE {phase}</div><h2>{title}</h2><p>{text}</p><div className="output-chips">{outputs.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section><section className="principles-section section-pad"><div className="section-shell principles-grid"><div className="section-heading"><div className="eyebrow dark"><span/>Delivery principles</div><h2>Practical controls that reduce project risk.</h2></div><div className="principles-list">{principles.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></div>)}</div></div></section><FinalCta/></main>}
